# Generated by Django 4.1.1 on 2022-09-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Computer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("processor_speed", models.CharField(max_length=100)),
                ("core_version", models.IntegerField()),
                ("number_of_usbport", models.IntegerField()),
                ("number_of_hdmiport", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="KeyBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_back_light", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=100)),
                ("screen_resolution", models.CharField(max_length=100)),
                (
                    "list_of_ports",
                    models.CharField(
                        choices=[
                            (
                                "Serial",
                                (("vga", "VGA"), ("hdmi", "HDMI"), ("hdmi", "HDMI")),
                            ),
                            (
                                "Parrallel",
                                (("vga", "VGA"), ("hdmi", "HDMI"), ("hdmi", "HDMI")),
                            ),
                        ],
                        default="1",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("1", "Wireless"), ("2", "Wired")],
                        default="1",
                        max_length=100,
                    ),
                ),
                ("colour", models.CharField(max_length=100)),
            ],
        ),
    ]
