# Generated by Django 4.1.1 on 2022-09-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manageitems", "0002_alter_keyboard_has_back_light"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyboard",
            name="has_back_light",
        ),
    ]
