# Generated by Django 4.1.1 on 2022-09-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manageitems", "0003_remove_keyboard_has_back_light"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyboard",
            name="has_back_light",
            field=models.BooleanField(default=False),
        ),
    ]
